import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const pages = ['index.html', 'introduction.html', 'web-based-mis.html', 'news.html', 'download.html', 'contact.html', '404.html'];
const cutoutPages = ['introduction.html', 'web-based-mis.html', 'news.html', 'download.html', 'contact.html'];
const archivePages = ['news.html', 'download.html'];
const discouragedPhrases = ['ai-generated', 'generated by ai', 'design strategy', 'modern redesign', 'world-class', 'mystery bundle', 'view mis', 'open overview'];
const contrastPairs = [
  ['primary text on canvas', '#111c16', '#f3f0e7', 4.5],
  ['muted text on canvas', '#53615a', '#f3f0e7', 4.5],
  ['muted text on white', '#53615a', '#ffffff', 4.5],
  ['white text on green', '#ffffff', '#0d3b2e', 4.5],
  ['lime text on dark green', '#d8f36f', '#082d23', 4.5],
  ['dark-section secondary text', '#c6d7cf', '#082d23', 4.5],
  ['warning text', '#685009', '#fff2c9', 4.5],
  ['green text on pale green', '#0d3b2e', '#e5efe8', 4.5],
];

/** Reads a UTF-8 project file. */
function read(path) {
  return readFile(resolve(root, path), 'utf8');
}

/** Records a validation failure when a requirement is not met. */
function expect(condition, message, failures) {
  if (!condition) failures.push(message);
}

/** Extracts local page and asset references from HTML. */
function localReferences(html) {
  return [...html.matchAll(/\b(?:href|src)=["']([^"']+)["']/g)]
    .map((match) => match[1])
    .filter((value) => !/^(?:https?:|mailto:|tel:|#)/.test(value))
    .map((value) => value.replace(/^\.\//, '').split(/[?#]/)[0]);
}

/** Returns the first captured value from a regular expression. */
function firstMatch(source, expression) {
  return source.match(expression)?.[1]?.trim() || '';
}

/** Validates one published HTML document. */
async function validatePage(path, failures, metadata) {
  const html = await read(path);
  const lower = html.toLowerCase();
  const title = firstMatch(html, /<title>([^<]+)<\/title>/);
  const description = firstMatch(html, /<meta\s+name="description"\s+content="([^"]+)"/);
  metadata.titles.push(title);
  metadata.descriptions.push(description);

  expect(title.length >= 20, `${path}: title is not descriptive`, failures);
  expect(description.length >= 70, `${path}: meta description does not clearly summarize the page`, failures);
  expect(/<meta\s+name="viewport"/.test(html), `${path}: missing viewport`, failures);
  expect(/<meta\s+name="theme-color"/.test(html), `${path}: missing theme color`, failures);
  expect(/<link\s+rel="canonical"/.test(html), `${path}: missing canonical link`, failures);
  expect(/<a class="skip-link"/.test(html), `${path}: missing skip link`, failures);
  expect(/<header\s+class="site-header"/.test(html), `${path}: missing static header`, failures);
  expect(/<footer\s+class="site-footer"/.test(html), `${path}: missing static footer`, failures);
  expect(/<main\b/.test(html), `${path}: missing main landmark`, failures);
  expect((html.match(/<h1\b/g) || []).length === 1, `${path}: expected one h1`, failures);
  expect(!/<site-(?:header|footer)>/.test(html), `${path}: runtime-only shared shell found`, failures);
  expect(!/href=["']#["']/.test(html), `${path}: placeholder link found`, failures);
  expect(!/style=["']/.test(html), `${path}: inline style found`, failures);
  expect(html.includes('assets/css/qa-fixes.css'), `${path}: missing QA stylesheet`, failures);
  expect(html.includes('assets/js/qa-fixes.js'), `${path}: missing QA module`, failures);

  for (const property of ['og:type', 'og:title', 'og:description', 'og:url', 'og:image']) {
    expect(html.includes(`property="${property}"`), `${path}: missing ${property}`, failures);
  }

  if (cutoutPages.includes(path)) {
    for (const className of ['page-hero__grid', 'page-hero__title-base', 'page-hero__title-cutout', 'page-hero__media']) {
      expect(html.includes(className), `${path}: missing ${className}`, failures);
    }
  }

  if (archivePages.includes(path)) {
    expect(!html.includes('assets/js/app.js'), `${path}: legacy archive controller is still loaded`, failures);
    expect(/lang="ne"/.test(html), `${path}: missing Nepali language metadata`, failures);
  }

  discouragedPhrases.forEach((phrase) => expect(!lower.includes(phrase), `${path}: discouraged phrase "${phrase}"`, failures));
  for (const tag of html.match(/<img\b[^>]*>/g) || []) expect(/\balt=["'][^"']*["']/.test(tag), `${path}: image missing alt text`, failures);

  for (const reference of localReferences(html)) {
    try {
      await access(resolve(root, reference));
    } catch {
      failures.push(`${path}: missing local reference ${reference}`);
    }
  }
}

/** Converts a hexadecimal colour to WCAG relative luminance. */
function luminance(hex) {
  const channels = hex.slice(1).match(/.{2}/g).map((value) => Number.parseInt(value, 16) / 255);
  const linear = channels.map((value) => (value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4));
  return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2];
}

/** Calculates the WCAG contrast ratio between two hexadecimal colours. */
function contrastRatio(foreground, background) {
  const values = [luminance(foreground), luminance(background)].sort((a, b) => b - a);
  return (values[0] + 0.05) / (values[1] + 0.05);
}

/** Checks JavaScript documentation and critical enhancement behavior. */
async function validateJavaScript(failures) {
  for (const path of ['assets/js/app.js', 'assets/js/flowchart.js', 'assets/js/qa-fixes.js']) {
    const source = await read(path);
    const functions = (source.match(/\bfunction\s+[A-Za-z0-9_]+\s*\(/g) || []).length;
    const documentation = (source.match(/\/\*\*/g) || []).length;
    expect(functions > 0, `${path}: no named functions found`, failures);
    expect(documentation >= functions, `${path}: every named function must be documented`, failures);
    expect(source.split('\n').length > 100, `${path}: source appears compressed`, failures);
  }
  const qa = await read('assets/js/qa-fixes.js');
  expect(qa.includes("setAttribute('aria-current', 'location')"), 'qa-fixes.js: incorrect TOC current state', failures);
  expect(qa.includes('https://web.archive.org/web/*/http://rismfp.gov.np/*'), 'qa-fixes.js: missing broad Wayback search', failures);
  expect(qa.includes('loadContrastStyles()'), 'qa-fixes.js: contrast stylesheet loader is missing', failures);
  expect(qa.includes('applyWebMisMicrocopy()'), 'qa-fixes.js: Web MIS copy enhancement is missing', failures);
}

/** Checks design-system and contrast stylesheets. */
async function validateCss(failures) {
  const base = await read('assets/css/style.css');
  const theme = await read('assets/css/agri-theme.css');
  const qa = await read('assets/css/qa-fixes.css');
  const contrast = await read('assets/css/seo-contrast.css');
  expect(base.includes('/* Design tokens'), 'style.css: missing token section', failures);
  expect(base.includes('/* Responsive layouts'), 'style.css: missing responsive section', failures);
  expect(qa.includes('.page-hero__title-cutout'), 'qa-fixes.css: missing cutout treatment', failures);
  expect(qa.includes(':lang(ne)'), 'qa-fixes.css: missing Nepali typography', failures);
  expect(/\.page-hero::before\s*\{[^}]*display\s*:\s*none/s.test(theme), 'agri-theme.css: legacy hero pseudo-image is active', failures);
  expect(/\.page-hero__media img\s*\{[^}]*position\s*:\s*absolute/s.test(theme), 'agri-theme.css: hero image does not cover its figure', failures);
  expect(!theme.includes('fonts.googleapis.com'), 'agri-theme.css: unused Google Fonts request found', failures);
  expect(contrast.includes('.metric-strip .source-note strong'), 'seo-contrast.css: provenance labels inherit metric styling', failures);
  expect(contrast.includes(':focus-visible'), 'seo-contrast.css: visible focus treatment is missing', failures);
  contrastPairs.forEach(([name, foreground, background, minimum]) => {
    const ratio = contrastRatio(foreground, background);
    expect(ratio >= minimum, `${name}: ${ratio.toFixed(2)}:1 is below ${minimum}:1`, failures);
  });
}

/** Checks static Vercel configuration. */
async function validateVercel(failures) {
  const config = JSON.parse(await read('vercel.json'));
  expect(config.framework === null, 'vercel.json: framework must be Other', failures);
  expect(config.installCommand === '', 'vercel.json: install command must be empty', failures);
  expect(config.buildCommand === '', 'vercel.json: build command must be empty', failures);
  expect(config.outputDirectory === '.', 'vercel.json: output directory must be repository root', failures);
}

/** Runs all repository checks. */
async function run() {
  const failures = [];
  const metadata = { titles: [], descriptions: [] };
  await Promise.all(pages.map((page) => validatePage(page, failures, metadata)));
  expect(new Set(metadata.titles).size === pages.length, 'SEO titles must be unique', failures);
  expect(new Set(metadata.descriptions).size === pages.length, 'SEO descriptions must be unique', failures);
  await validateJavaScript(failures);
  await validateCss(failures);
  await validateVercel(failures);

  if (failures.length) {
    console.error('\nValidation failed:\n');
    failures.forEach((failure) => console.error(`- ${failure}`));
    process.exitCode = 1;
    return;
  }
  console.log(`Validation passed for ${pages.length} pages, unique SEO metadata, JavaScript behavior, and WCAG contrast pairs.`);
}

await run();
