import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

/** Root directory used to resolve files during validation. */
const root = resolve(import.meta.dirname, '..');

/** Pages published by GitHub Pages. */
const pages = ['index.html', 'introduction.html', 'web-based-mis.html', 'news.html', 'download.html', 'contact.html', '404.html'];

/** Phrases intentionally excluded from the public-facing copy. */
const discouragedPhrases = ['ai-generated', 'generated by ai', 'design strategy', 'modern redesign', 'world-class', 'mystery bundle'];

/**
 * Reads a UTF-8 project file.
 * @param {string} path Relative file path.
 * @returns {Promise<string>} File contents.
 */
function read(path) {
  return readFile(resolve(root, path), 'utf8');
}

/**
 * Records a validation failure when a requirement is not met.
 * @param {boolean} condition Result of the requirement.
 * @param {string} message Failure description.
 * @param {string[]} failures Shared failure list.
 */
function expect(condition, message, failures) {
  if (!condition) failures.push(message);
}

/**
 * Extracts local page and asset references from HTML.
 * @param {string} html HTML document source.
 * @returns {string[]} Relative references.
 */
function localReferences(html) {
  const references = [];
  const pattern = /\b(?:href|src)=["']([^"']+)["']/g;
  let match;

  while ((match = pattern.exec(html)) !== null) {
    const value = match[1];
    if (!/^(?:https?:|mailto:|tel:|#)/.test(value)) {
      references.push(value.replace(/^\.\//, '').split(/[?#]/)[0]);
    }
  }

  return references;
}

/**
 * Validates one published HTML document.
 * @param {string} path Relative HTML path.
 * @param {string[]} failures Shared failure list.
 * @returns {Promise<void>}
 */
async function validatePage(path, failures) {
  const html = await read(path);
  const lower = html.toLowerCase();

  expect(/<title>[^<]+<\/title>/.test(html), `${path}: missing title`, failures);
  expect(/<meta\s+name="viewport"/.test(html), `${path}: missing viewport`, failures);
  expect(/<main\b/.test(html), `${path}: missing main landmark`, failures);
  expect(/<h1\b/.test(html), `${path}: missing h1`, failures);
  expect(/<!--/.test(html), `${path}: missing structural comments`, failures);
  expect(!/href=["']#["']/.test(html), `${path}: placeholder link found`, failures);
  expect(!/style=["']/.test(html), `${path}: inline style found`, failures);

  discouragedPhrases.forEach((phrase) => {
    expect(!lower.includes(phrase), `${path}: discouraged phrase “${phrase}”`, failures);
  });

  for (const tag of html.match(/<img\b[^>]*>/g) || []) {
    expect(/\balt=["'][^"']*["']/.test(tag), `${path}: image missing alt text`, failures);
  }

  for (const reference of localReferences(html)) {
    try {
      await access(resolve(root, reference));
    } catch {
      failures.push(`${path}: missing local reference ${reference}`);
    }
  }
}

/**
 * Checks JavaScript formatting and function documentation.
 * @param {string[]} failures Shared failure list.
 * @returns {Promise<void>}
 */
async function validateJavaScript(failures) {
  const source = await read('assets/js/app.js');
  const functions = (source.match(/\bfunction\s+[A-Za-z0-9_]+\s*\(/g) || []).length;
  const documentation = (source.match(/\/\*\*/g) || []).length;
  expect(functions > 0, 'app.js: no named functions found', failures);
  expect(documentation >= functions, 'app.js: every function must be documented', failures);
  expect(source.split('\n').length > 100, 'app.js: source appears compressed', failures);
}

/**
 * Checks that CSS remains organised into labelled source sections.
 * @param {string[]} failures Shared failure list.
 * @returns {Promise<void>}
 */
async function validateCss(failures) {
  const source = await read('assets/css/style.css');
  expect(source.includes('/* Design tokens'), 'style.css: missing token section', failures);
  expect(source.includes('/* Responsive layouts'), 'style.css: missing responsive section', failures);
  expect(source.split('\n').length > 200, 'style.css: source appears compressed', failures);
}

/**
 * Runs all repository checks and returns a failing exit code when needed.
 * @returns {Promise<void>}
 */
async function run() {
  const failures = [];
  await Promise.all(pages.map((page) => validatePage(page, failures)));
  await validateJavaScript(failures);
  await validateCss(failures);

  if (failures.length) {
    console.error('\nValidation failed:\n');
    failures.forEach((failure) => console.error(`- ${failure}`));
    process.exitCode = 1;
    return;
  }

  console.log(`Validation passed for ${pages.length} pages, shared JavaScript, and CSS.`);
}

await run();
