import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const pages = ['index.html', 'introduction.html', 'web-based-mis.html', 'news.html', 'download.html', 'contact.html', '404.html'];
const cutoutPages = ['introduction.html', 'web-based-mis.html', 'news.html', 'download.html', 'contact.html'];
const archivePages = ['news.html', 'download.html'];
const discouragedPhrases = ['ai-generated', 'generated by ai', 'design strategy', 'modern redesign', 'world-class', 'mystery bundle', 'view mis', 'open overview'];
const contrastPairs = [
  ['primary text on canvas', '#111c16', '#f3f0e7', 4.5],
  ['muted text on canvas', '#53615a', '#f3f0e7', 4.5],
  ['provenance text on white', '#33423b', '#ffffff', 4.5],
  ['footer secondary text on canvas', '#435149', '#f3f0e7', 4.5],
  ['footer heading on canvas', '#0d3b2e', '#f3f0e7', 4.5],
  ['white text on green', '#ffffff', '#0d3b2e', 4.5],
  ['lime text on dark green', '#d8f36f', '#082d23', 4.5],
  ['dark-section secondary text', '#c6d7cf', '#082d23', 4.5],
  ['warning text', '#685009', '#fff2c9', 4.5],
];

function read(path) { return readFile(resolve(root, path), 'utf8'); }
function expect(condition, message, failures) { if (!condition) failures.push(message); }
function firstMatch(source, expression) { return source.match(expression)?.[1]?.trim() || ''; }

function localReferences(html) {
  return [...html.matchAll(/\b(?:href|src)=["']([^"']+)["']/g)]
    .map((match) => match[1])
    .filter((value) => !/^(?:https?:|mailto:|tel:|#)/.test(value))
    .map((value) => value.replace(/^\.\//, '').split(/[?#]/)[0]);
}

async function validatePage(path, failures, metadata) {
  const html = await read(path);
  const lower = html.toLowerCase();
  const title = firstMatch(html, /<title>([^<]+)<\/title>/);
  const description = firstMatch(html, /<meta\s+name="description"\s+content="([^"]+)"/);
  metadata.titles.push(title);
  metadata.descriptions.push(description);

  expect(title.length >= 20, `${path}: title is not descriptive`, failures);
  expect(description.length >= 70, `${path}: meta description is too short`, failures);
  expect(/<meta\s+name="viewport"/.test(html), `${path}: missing viewport`, failures);
  expect(/<link\s+rel="canonical"/.test(html), `${path}: missing canonical link`, failures);
  expect(/<a class="skip-link"/.test(html), `${path}: missing skip link`, failures);
  expect(/<header\s+class="site-header"/.test(html), `${path}: missing static header`, failures);
  expect(/<footer\s+class="site-footer"/.test(html), `${path}: missing static footer`, failures);
  expect((html.match(/<h1\b/g) || []).length === 1, `${path}: expected one h1`, failures);
  expect(!html.includes('assets/js/app.js'), `${path}: obsolete app.js is still loaded`, failures);
  expect(html.includes('assets/js/qa-fixes.js'), `${path}: missing enhancement module`, failures);
  expect(html.includes('assets/css/seo-contrast.css'), `${path}: contrast stylesheet is not static`, failures);
  expect(!/href=["']#["']/.test(html), `${path}: placeholder link found`, failures);
  expect(!/style=["']/.test(html), `${path}: inline style found`, failures);

  for (const property of ['og:type', 'og:title', 'og:description', 'og:url', 'og:image']) {
    expect(html.includes(`property="${property}"`), `${path}: missing ${property}`, failures);
  }
  if (cutoutPages.includes(path)) {
    for (const className of ['page-hero__grid', 'page-hero__title-base', 'page-hero__title-cutout', 'page-hero__media']) {
      expect(html.includes(className), `${path}: missing ${className}`, failures);
    }
  }
  if (archivePages.includes(path)) expect(/lang="ne"/.test(html), `${path}: missing Nepali language metadata`, failures);
  discouragedPhrases.forEach((phrase) => expect(!lower.includes(phrase), `${path}: discouraged phrase "${phrase}"`, failures));
  for (const tag of html.match(/<img\b[^>]*>/g) || []) expect(/\balt=["'][^"']*["']/.test(tag), `${path}: image missing alt text`, failures);
  for (const reference of localReferences(html)) {
    try { await access(resolve(root, reference)); } catch { failures.push(`${path}: missing local reference ${reference}`); }
  }
}

function luminance(hex) {
  const channels = hex.slice(1).match(/.{2}/g).map((value) => Number.parseInt(value, 16) / 255);
  const linear = channels.map((value) => (value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4));
  return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2];
}
function contrastRatio(foreground, background) {
  const values = [luminance(foreground), luminance(background)].sort((a, b) => b - a);
  return (values[0] + 0.05) / (values[1] + 0.05);
}

async function validateJavaScript(failures) {
  for (const path of ['assets/js/flowchart.js', 'assets/js/qa-fixes.js', 'scripts/browser-check.mjs']) {
    const source = await read(path);
    expect(source.length > 500, `${path}: source appears incomplete`, failures);
  }
  const qa = await read('assets/js/qa-fixes.js');
  expect(qa.includes("setAttribute('aria-current', 'location')"), 'qa-fixes.js: incorrect TOC current state', failures);
  expect(qa.includes('ARCHIVE_SORTS.has'), 'qa-fixes.js: archive sort values are not validated', failures);
  expect(qa.includes('Copy failed'), 'qa-fixes.js: clipboard failures are not handled', failures);
  expect(!qa.includes('loadContrastStyles'), 'qa-fixes.js: contrast CSS is still injected at runtime', failures);
  expect(!qa.includes('applyWebMisMicrocopy'), 'qa-fixes.js: SEO copy is still changed at runtime', failures);

  const flowchart = await read('assets/js/flowchart.js');
  expect(flowchart.includes('function fitView'), 'flowchart.js: fit-to-view behavior is missing', failures);
  expect(flowchart.includes('constrainTranslation'), 'flowchart.js: pan bounds are missing', failures);
  expect(flowchart.includes('event.ctrlKey') && flowchart.includes('event.metaKey'), 'flowchart.js: ordinary scrolling is intercepted', failures);
  expect(flowchart.includes("setAttribute('aria-pressed'"), 'flowchart.js: selected node state is not exposed', failures);
}

async function validateCss(failures) {
  const theme = await read('assets/css/agri-theme.css');
  const qa = await read('assets/css/qa-fixes.css');
  const contrast = await read('assets/css/seo-contrast.css');
  const flowchart = await read('assets/css/flowchart.css');
  expect(qa.includes('.page-hero__title-cutout'), 'qa-fixes.css: cutout treatment is missing', failures);
  expect(qa.includes(':lang(ne)'), 'qa-fixes.css: Nepali typography is missing', failures);
  expect(/\.page-hero::before\s*\{[^}]*display\s*:\s*none/s.test(theme), 'agri-theme.css: legacy hero pseudo-image is active', failures);
  expect(contrast.includes('.metric-strip .source-note > span'), 'seo-contrast.css: provenance text loses to metric styling', failures);
  expect(contrast.includes('@media (max-width: 1120px)'), 'seo-contrast.css: navigation breakpoint is missing', failures);
  expect(flowchart.includes('touch-action: pan-y'), 'flowchart.css: touch scrolling is trapped', failures);
  expect(!flowchart.includes('Manrope'), 'flowchart.css: removed font is still referenced', failures);
  contrastPairs.forEach(([name, foreground, background, minimum]) => {
    const ratio = contrastRatio(foreground, background);
    expect(ratio >= minimum, `${name}: ${ratio.toFixed(2)}:1 is below ${minimum}:1`, failures);
  });
}

async function validateSpecialCases(failures) {
  const home = await read('index.html');
  expect(home.includes('rel="canonical" href="https://nischhalsubba.github.io/rismfp-ui/"'), 'index.html: homepage canonical is not the public root', failures);
  const mis = await read('web-based-mis.html');
  expect(mis.includes('<title>RISMFP Web MIS Architecture | Nepal Agriculture Project Monitoring</title>'), 'web-based-mis.html: final title is not static', failures);
  expect(mis.includes('data-flowchart-action="reset">Fit diagram</button>'), 'web-based-mis.html: Fit diagram control is missing', failures);
  expect(!mis.includes('role="application"'), 'web-based-mis.html: role application remains', failures);
  const contact = await read('contact.html');
  expect(!/href="(?:tel:|mailto:)/.test(contact), 'contact.html: unverified contact details remain actionable', failures);
}

async function run() {
  const failures = [];
  const metadata = { titles: [], descriptions: [] };
  await Promise.all(pages.map((page) => validatePage(page, failures, metadata)));
  expect(new Set(metadata.titles).size === pages.length, 'SEO titles must be unique', failures);
  expect(new Set(metadata.descriptions).size === pages.length, 'SEO descriptions must be unique', failures);
  await validateJavaScript(failures);
  await validateCss(failures);
  await validateSpecialCases(failures);
  const config = JSON.parse(await read('vercel.json'));
  expect(config.framework === null && config.outputDirectory === '.', 'vercel.json: static configuration changed', failures);

  if (failures.length) {
    console.error('\nValidation failed:\n');
    failures.forEach((failure) => console.error(`- ${failure}`));
    process.exitCode = 1;
  } else {
    console.log(`Static validation passed for ${pages.length} pages and final QA safeguards.`);
  }
}

await run();